In [2]:
#import necessary libraries
import pandas as pd
import json

In [3]:
with open("t20_wc_match_results.json") as f:
    data=json.load(f)
data

[{'matchSummary': [{'team1': 'Namibia',
    'team2': 'Sri Lanka',
    'winner': 'Namibia',
    'margin': '55 runs',
    'ground': 'Geelong',
    'matchDate': 'Oct 16, 2022',
    'scorecard': 'T20I # 1823'},
   {'team1': 'Netherlands',
    'team2': 'U.A.E.',
    'winner': 'Netherlands',
    'margin': '3 wickets',
    'ground': 'Geelong',
    'matchDate': 'Oct 16, 2022',
    'scorecard': 'T20I # 1825'},
   {'team1': 'Scotland',
    'team2': 'West Indies',
    'winner': 'Scotland',
    'margin': '42 runs',
    'ground': 'Hobart',
    'matchDate': 'Oct 17, 2022',
    'scorecard': 'T20I # 1826'},
   {'team1': 'Ireland',
    'team2': 'Zimbabwe',
    'winner': 'Zimbabwe',
    'margin': '31 runs',
    'ground': 'Hobart',
    'matchDate': 'Oct 17, 2022',
    'scorecard': 'T20I # 1828'},
   {'team1': 'Namibia',
    'team2': 'Netherlands',
    'winner': 'Netherlands',
    'margin': '5 wickets',
    'ground': 'Geelong',
    'matchDate': 'Oct 18, 2022',
    'scorecard': 'T20I # 1830'},
   {'team1': 'Sri Lanka',
    'team2': 'U.A.E.',
    'winner': 'Sri Lanka',
    'margin': '79 runs',
    'ground': 'Geelong',
    'matchDate': 'Oct 18, 2022',
    'scorecard': 'T20I # 1832'},
   {'team1': 'Ireland',
    'team2': 'Scotland',
    'winner': 'Ireland',
    'margin': '6 wickets',
    'ground': 'Hobart',
    'matchDate': 'Oct 19, 2022',
    'scorecard': 'T20I # 1833'},
   {'team1': 'West Indies',
    'team2': 'Zimbabwe',
    'winner': 'West Indies',
    'margin': '31 runs',
    'ground': 'Hobart',
    'matchDate': 'Oct 19, 2022',
    'scorecard': 'T20I # 1834'},
   {'team1': 'Netherlands',
    'team2': 'Sri Lanka',
    'winner': 'Sri Lanka',
    'margin': '16 runs',
    'ground': 'Geelong',
    'matchDate': 'Oct 20, 2022',
    'scorecard': 'T20I # 1835'},
   {'team1': 'Namibia',
    'team2': 'U.A.E.',
    'winner': 'U.A.E.',
    'margin': '7 runs',
    'ground': 'Geelong',
    'matchDate': 'Oct 20, 2022',
    'scorecard': 'T20I # 1836'},
   {'team1': 'Ireland',
    'team2': 'West Indies',
    'winner': 'Ireland',
    'margin': '9 wickets',
    'ground': 'Hobart',
    'matchDate': 'Oct 21, 2022',
    'scorecard': 'T20I # 1837'},
   {'team1': 'Scotland',
    'team2': 'Zimbabwe',
    'winner': 'Zimbabwe',
    'margin': '5 wickets',
    'ground': 'Hobart',
    'matchDate': 'Oct 21, 2022',
    'scorecard': 'T20I # 1838'},
   {'team1': 'Australia',
    'team2': 'New Zealand',
    'winner': 'New Zealand',
    'margin': '89 runs',
    'ground': 'Sydney',
    'matchDate': 'Oct 22, 2022',
    'scorecard': 'T20I # 1839'},
   {'team1': 'Afghanistan',
    'team2': 'England',
    'winner': 'England',
    'margin': '5 wickets',
    'ground': 'Perth',
    'matchDate': 'Oct 22, 2022',
    'scorecard': 'T20I # 1840'},
   {'team1': 'Ireland',
    'team2': 'Sri Lanka',
    'winner': 'Sri Lanka',
    'margin': '9 wickets',
    'ground': 'Hobart',
    'matchDate': 'Oct 23, 2022',
    'scorecard': 'T20I # 1841'},
   {'team1': 'India',
    'team2': 'Pakistan',
    'winner': 'India',
    'margin': '4 wickets',
    'ground': 'Melbourne',
    'matchDate': 'Oct 23, 2022',
    'scorecard': 'T20I # 1842'},
   {'team1': 'Bangladesh',
    'team2': 'Netherlands',
    'winner': 'Bangladesh',
    'margin': '9 runs',
    'ground': 'Hobart',
    'matchDate': 'Oct 24, 2022',
    'scorecard': 'T20I # 1843'},
   {'team1': 'South Africa',
    'team2': 'Zimbabwe',
    'winner': 'no result',
    'margin': '',
    'ground': 'Hobart',
    'matchDate': 'Oct 24, 2022',
    'scorecard': 'T20I # 1844'},
   {'team1': 'Australia',
    'team2': 'Sri Lanka',
    'winner': 'Australia',
    'margin': '7 wickets',
    'ground': 'Perth',
    'matchDate': 'Oct 25, 2022',
    'scorecard': 'T20I # 1845'},
   {'team1': 'England',
    'team2': 'Ireland',
    'winner': 'Ireland',
    'margin': '5 runs',
    'ground': 'Melbourne',
    'matchDate': 'Oct 26, 2022',
    'scorecard': 'T20I # 1846'},
   {'team1': 'Afghanistan',
    'team2': 'New Zealand',
    'winner': 'abandoned',
    'margin': '',
    'ground': 'Melbourne',
    'matchDate': 'Oct 26, 2022',
    'scorecard': 'T20I # 1846a'},
   {'team1': 'Bangladesh',
    'team2': 'South Africa',
    'winner': 'South Africa',
    'margin': '104 runs',
    'ground': 'Sydney',
    'matchDate': 'Oct 27, 2022',
    'scorecard': 'T20I # 1847'},
   {'team1': 'India',
    'team2': 'Netherlands',
    'winner': 'India',
    'margin': '56 runs',
    'ground': 'Sydney',
    'matchDate': 'Oct 27, 2022',
    'scorecard': 'T20I # 1848'},
   {'team1': 'Pakistan',
    'team2': 'Zimbabwe',
    'winner': 'Zimbabwe',
    'margin': '1 run',
    'ground': 'Perth',
    'matchDate': 'Oct 27, 2022',
    'scorecard': 'T20I # 1849'},
   {'team1': 'Afghanistan',
    'team2': 'Ireland',
    'winner': 'abandoned',
    'margin': '',
    'ground': 'Melbourne',
    'matchDate': 'Oct 28, 2022',
    'scorecard': 'T20I # 1849a'},
   {'team1': 'Australia',
    'team2': 'England',
    'winner': 'abandoned',
    'margin': '',
    'ground': 'Melbourne',
    'matchDate': 'Oct 28, 2022',
    'scorecard': 'T20I # 1849b'},
   {'team1': 'New Zealand',
    'team2': 'Sri Lanka',
    'winner': 'New Zealand',
    'margin': '65 runs',
    'ground': 'Sydney',
    'matchDate': 'Oct 29, 2022',
    'scorecard': 'T20I # 1850'},
   {'team1': 'Bangladesh',
    'team2': 'Zimbabwe',
    'winner': 'Bangladesh',
    'margin': '3 runs',
    'ground': 'Brisbane',
    'matchDate': 'Oct 30, 2022',
    'scorecard': 'T20I # 1851'},
   {'team1': 'Netherlands',
    'team2': 'Pakistan',
    'winner': 'Pakistan',
    'margin': '6 wickets',
    'ground': 'Perth',
    'matchDate': 'Oct 30, 2022',
    'scorecard': 'T20I # 1852'},
   {'team1': 'India',
    'team2': 'South Africa',
    'winner': 'South Africa',
    'margin': '5 wickets',
    'ground': 'Perth',
    'matchDate': 'Oct 30, 2022',
    'scorecard': 'T20I # 1853'},
   {'team1': 'Australia',
    'team2': 'Ireland',
    'winner': 'Australia',
    'margin': '42 runs',
    'ground': 'Brisbane',
    'matchDate': 'Oct 31, 2022',
    'scorecard': 'T20I # 1855'},
   {'team1': 'Afghanistan',
    'team2': 'Sri Lanka',
    'winner': 'Sri Lanka',
    'margin': '6 wickets',
    'ground': 'Brisbane',
    'matchDate': 'Nov 1, 2022',
    'scorecard': 'T20I # 1856'},
   {'team1': 'England',
    'team2': 'New Zealand',
    'winner': 'England',
    'margin': '20 runs',
    'ground': 'Brisbane',
    'matchDate': 'Nov 1, 2022',
    'scorecard': 'T20I # 1858'},
   {'team1': 'Netherlands',
    'team2': 'Zimbabwe',
    'winner': 'Netherlands',
    'margin': '5 wickets',
    'ground': 'Adelaide',
    'matchDate': 'Nov 2, 2022',
    'scorecard': 'T20I # 1859'},
   {'team1': 'Bangladesh',
    'team2': 'India',
    'winner': 'India',
    'margin': '5 runs',
    'ground': 'Adelaide',
    'matchDate': 'Nov 2, 2022',
    'scorecard': 'T20I # 1860'},
   {'team1': 'Pakistan',
    'team2': 'South Africa',
    'winner': 'Pakistan',
    'margin': '33 runs',
    'ground': 'Sydney',
    'matchDate': 'Nov 3, 2022',
    'scorecard': 'T20I # 1861'},
   {'team1': 'Ireland',
    'team2': 'New Zealand',
    'winner': 'New Zealand',
    'margin': '35 runs',
    'ground': 'Adelaide',
    'matchDate': 'Nov 4, 2022',
    'scorecard': 'T20I # 1862'},
   {'team1': 'Australia',
    'team2': 'Afghanistan',
    'winner': 'Australia',
    'margin': '4 runs',
    'ground': 'Adelaide',
    'matchDate': 'Nov 4, 2022',
    'scorecard': 'T20I # 1864'},
   {'team1': 'England',
    'team2': 'Sri Lanka',
    'winner': 'England',
    'margin': '4 wickets',
    'ground': 'Sydney',
    'matchDate': 'Nov 5, 2022',
    'scorecard': 'T20I # 1867'},
   {'team1': 'Netherlands',
    'team2': 'South Africa',
    'winner': 'Netherlands',
    'margin': '13 runs',
    'ground': 'Adelaide',
    'matchDate': 'Nov 6, 2022',
    'scorecard': 'T20I # 1871'},
   {'team1': 'Bangladesh',
    'team2': 'Pakistan',
    'winner': 'Pakistan',
    'margin': '5 wickets',
    'ground': 'Adelaide',
    'matchDate': 'Nov 6, 2022',
    'scorecard': 'T20I # 1872'},
   {'team1': 'India',
    'team2': 'Zimbabwe',
    'winner': 'India',
    'margin': '71 runs',
    'ground': 'Melbourne',
    'matchDate': 'Nov 6, 2022',
    'scorecard': 'T20I # 1873'},
   {'team1': 'New Zealand',
    'team2': 'Pakistan',
    'winner': 'Pakistan',
    'margin': '7 wickets',
    'ground': 'Sydney',
    'matchDate': 'Nov 9, 2022',
    'scorecard': 'T20I # 1877'},
   {'team1': 'England',
    'team2': 'India',
    'winner': 'England',
    'margin': '10 wickets',
    'ground': 'Adelaide',
    'matchDate': 'Nov 10, 2022',
    'scorecard': 'T20I # 1878'},
   {'team1': 'England',
    'team2': 'Pakistan',
    'winner': 'England',
    'margin': '5 wickets',
    'ground': 'Melbourne',
    'matchDate': 'Nov 13, 2022',
    'scorecard': 'T20I # 1879'}]}]

In [4]:
#the main list where we have all results is
with open("t20_wc_match_results.json") as f:
    data=json.load(f)
data[0]["matchSummary"]

[{'team1': 'Namibia',
  'team2': 'Sri Lanka',
  'winner': 'Namibia',
  'margin': '55 runs',
  'ground': 'Geelong',
  'matchDate': 'Oct 16, 2022',
  'scorecard': 'T20I # 1823'},
 {'team1': 'Netherlands',
  'team2': 'U.A.E.',
  'winner': 'Netherlands',
  'margin': '3 wickets',
  'ground': 'Geelong',
  'matchDate': 'Oct 16, 2022',
  'scorecard': 'T20I # 1825'},
 {'team1': 'Scotland',
  'team2': 'West Indies',
  'winner': 'Scotland',
  'margin': '42 runs',
  'ground': 'Hobart',
  'matchDate': 'Oct 17, 2022',
  'scorecard': 'T20I # 1826'},
 {'team1': 'Ireland',
  'team2': 'Zimbabwe',
  'winner': 'Zimbabwe',
  'margin': '31 runs',
  'ground': 'Hobart',
  'matchDate': 'Oct 17, 2022',
  'scorecard': 'T20I # 1828'},
 {'team1': 'Namibia',
  'team2': 'Netherlands',
  'winner': 'Netherlands',
  'margin': '5 wickets',
  'ground': 'Geelong',
  'matchDate': 'Oct 18, 2022',
  'scorecard': 'T20I # 1830'},
 {'team1': 'Sri Lanka',
  'team2': 'U.A.E.',
  'winner': 'Sri Lanka',
  'margin': '79 runs',
  'ground': 'Geelong',
  'matchDate': 'Oct 18, 2022',
  'scorecard': 'T20I # 1832'},
 {'team1': 'Ireland',
  'team2': 'Scotland',
  'winner': 'Ireland',
  'margin': '6 wickets',
  'ground': 'Hobart',
  'matchDate': 'Oct 19, 2022',
  'scorecard': 'T20I # 1833'},
 {'team1': 'West Indies',
  'team2': 'Zimbabwe',
  'winner': 'West Indies',
  'margin': '31 runs',
  'ground': 'Hobart',
  'matchDate': 'Oct 19, 2022',
  'scorecard': 'T20I # 1834'},
 {'team1': 'Netherlands',
  'team2': 'Sri Lanka',
  'winner': 'Sri Lanka',
  'margin': '16 runs',
  'ground': 'Geelong',
  'matchDate': 'Oct 20, 2022',
  'scorecard': 'T20I # 1835'},
 {'team1': 'Namibia',
  'team2': 'U.A.E.',
  'winner': 'U.A.E.',
  'margin': '7 runs',
  'ground': 'Geelong',
  'matchDate': 'Oct 20, 2022',
  'scorecard': 'T20I # 1836'},
 {'team1': 'Ireland',
  'team2': 'West Indies',
  'winner': 'Ireland',
  'margin': '9 wickets',
  'ground': 'Hobart',
  'matchDate': 'Oct 21, 2022',
  'scorecard': 'T20I # 1837'},
 {'team1': 'Scotland',
  'team2': 'Zimbabwe',
  'winner': 'Zimbabwe',
  'margin': '5 wickets',
  'ground': 'Hobart',
  'matchDate': 'Oct 21, 2022',
  'scorecard': 'T20I # 1838'},
 {'team1': 'Australia',
  'team2': 'New Zealand',
  'winner': 'New Zealand',
  'margin': '89 runs',
  'ground': 'Sydney',
  'matchDate': 'Oct 22, 2022',
  'scorecard': 'T20I # 1839'},
 {'team1': 'Afghanistan',
  'team2': 'England',
  'winner': 'England',
  'margin': '5 wickets',
  'ground': 'Perth',
  'matchDate': 'Oct 22, 2022',
  'scorecard': 'T20I # 1840'},
 {'team1': 'Ireland',
  'team2': 'Sri Lanka',
  'winner': 'Sri Lanka',
  'margin': '9 wickets',
  'ground': 'Hobart',
  'matchDate': 'Oct 23, 2022',
  'scorecard': 'T20I # 1841'},
 {'team1': 'India',
  'team2': 'Pakistan',
  'winner': 'India',
  'margin': '4 wickets',
  'ground': 'Melbourne',
  'matchDate': 'Oct 23, 2022',
  'scorecard': 'T20I # 1842'},
 {'team1': 'Bangladesh',
  'team2': 'Netherlands',
  'winner': 'Bangladesh',
  'margin': '9 runs',
  'ground': 'Hobart',
  'matchDate': 'Oct 24, 2022',
  'scorecard': 'T20I # 1843'},
 {'team1': 'South Africa',
  'team2': 'Zimbabwe',
  'winner': 'no result',
  'margin': '',
  'ground': 'Hobart',
  'matchDate': 'Oct 24, 2022',
  'scorecard': 'T20I # 1844'},
 {'team1': 'Australia',
  'team2': 'Sri Lanka',
  'winner': 'Australia',
  'margin': '7 wickets',
  'ground': 'Perth',
  'matchDate': 'Oct 25, 2022',
  'scorecard': 'T20I # 1845'},
 {'team1': 'England',
  'team2': 'Ireland',
  'winner': 'Ireland',
  'margin': '5 runs',
  'ground': 'Melbourne',
  'matchDate': 'Oct 26, 2022',
  'scorecard': 'T20I # 1846'},
 {'team1': 'Afghanistan',
  'team2': 'New Zealand',
  'winner': 'abandoned',
  'margin': '',
  'ground': 'Melbourne',
  'matchDate': 'Oct 26, 2022',
  'scorecard': 'T20I # 1846a'},
 {'team1': 'Bangladesh',
  'team2': 'South Africa',
  'winner': 'South Africa',
  'margin': '104 runs',
  'ground': 'Sydney',
  'matchDate': 'Oct 27, 2022',
  'scorecard': 'T20I # 1847'},
 {'team1': 'India',
  'team2': 'Netherlands',
  'winner': 'India',
  'margin': '56 runs',
  'ground': 'Sydney',
  'matchDate': 'Oct 27, 2022',
  'scorecard': 'T20I # 1848'},
 {'team1': 'Pakistan',
  'team2': 'Zimbabwe',
  'winner': 'Zimbabwe',
  'margin': '1 run',
  'ground': 'Perth',
  'matchDate': 'Oct 27, 2022',
  'scorecard': 'T20I # 1849'},
 {'team1': 'Afghanistan',
  'team2': 'Ireland',
  'winner': 'abandoned',
  'margin': '',
  'ground': 'Melbourne',
  'matchDate': 'Oct 28, 2022',
  'scorecard': 'T20I # 1849a'},
 {'team1': 'Australia',
  'team2': 'England',
  'winner': 'abandoned',
  'margin': '',
  'ground': 'Melbourne',
  'matchDate': 'Oct 28, 2022',
  'scorecard': 'T20I # 1849b'},
 {'team1': 'New Zealand',
  'team2': 'Sri Lanka',
  'winner': 'New Zealand',
  'margin': '65 runs',
  'ground': 'Sydney',
  'matchDate': 'Oct 29, 2022',
  'scorecard': 'T20I # 1850'},
 {'team1': 'Bangladesh',
  'team2': 'Zimbabwe',
  'winner': 'Bangladesh',
  'margin': '3 runs',
  'ground': 'Brisbane',
  'matchDate': 'Oct 30, 2022',
  'scorecard': 'T20I # 1851'},
 {'team1': 'Netherlands',
  'team2': 'Pakistan',
  'winner': 'Pakistan',
  'margin': '6 wickets',
  'ground': 'Perth',
  'matchDate': 'Oct 30, 2022',
  'scorecard': 'T20I # 1852'},
 {'team1': 'India',
  'team2': 'South Africa',
  'winner': 'South Africa',
  'margin': '5 wickets',
  'ground': 'Perth',
  'matchDate': 'Oct 30, 2022',
  'scorecard': 'T20I # 1853'},
 {'team1': 'Australia',
  'team2': 'Ireland',
  'winner': 'Australia',
  'margin': '42 runs',
  'ground': 'Brisbane',
  'matchDate': 'Oct 31, 2022',
  'scorecard': 'T20I # 1855'},
 {'team1': 'Afghanistan',
  'team2': 'Sri Lanka',
  'winner': 'Sri Lanka',
  'margin': '6 wickets',
  'ground': 'Brisbane',
  'matchDate': 'Nov 1, 2022',
  'scorecard': 'T20I # 1856'},
 {'team1': 'England',
  'team2': 'New Zealand',
  'winner': 'England',
  'margin': '20 runs',
  'ground': 'Brisbane',
  'matchDate': 'Nov 1, 2022',
  'scorecard': 'T20I # 1858'},
 {'team1': 'Netherlands',
  'team2': 'Zimbabwe',
  'winner': 'Netherlands',
  'margin': '5 wickets',
  'ground': 'Adelaide',
  'matchDate': 'Nov 2, 2022',
  'scorecard': 'T20I # 1859'},
 {'team1': 'Bangladesh',
  'team2': 'India',
  'winner': 'India',
  'margin': '5 runs',
  'ground': 'Adelaide',
  'matchDate': 'Nov 2, 2022',
  'scorecard': 'T20I # 1860'},
 {'team1': 'Pakistan',
  'team2': 'South Africa',
  'winner': 'Pakistan',
  'margin': '33 runs',
  'ground': 'Sydney',
  'matchDate': 'Nov 3, 2022',
  'scorecard': 'T20I # 1861'},
 {'team1': 'Ireland',
  'team2': 'New Zealand',
  'winner': 'New Zealand',
  'margin': '35 runs',
  'ground': 'Adelaide',
  'matchDate': 'Nov 4, 2022',
  'scorecard': 'T20I # 1862'},
 {'team1': 'Australia',
  'team2': 'Afghanistan',
  'winner': 'Australia',
  'margin': '4 runs',
  'ground': 'Adelaide',
  'matchDate': 'Nov 4, 2022',
  'scorecard': 'T20I # 1864'},
 {'team1': 'England',
  'team2': 'Sri Lanka',
  'winner': 'England',
  'margin': '4 wickets',
  'ground': 'Sydney',
  'matchDate': 'Nov 5, 2022',
  'scorecard': 'T20I # 1867'},
 {'team1': 'Netherlands',
  'team2': 'South Africa',
  'winner': 'Netherlands',
  'margin': '13 runs',
  'ground': 'Adelaide',
  'matchDate': 'Nov 6, 2022',
  'scorecard': 'T20I # 1871'},
 {'team1': 'Bangladesh',
  'team2': 'Pakistan',
  'winner': 'Pakistan',
  'margin': '5 wickets',
  'ground': 'Adelaide',
  'matchDate': 'Nov 6, 2022',
  'scorecard': 'T20I # 1872'},
 {'team1': 'India',
  'team2': 'Zimbabwe',
  'winner': 'India',
  'margin': '71 runs',
  'ground': 'Melbourne',
  'matchDate': 'Nov 6, 2022',
  'scorecard': 'T20I # 1873'},
 {'team1': 'New Zealand',
  'team2': 'Pakistan',
  'winner': 'Pakistan',
  'margin': '7 wickets',
  'ground': 'Sydney',
  'matchDate': 'Nov 9, 2022',
  'scorecard': 'T20I # 1877'},
 {'team1': 'England',
  'team2': 'India',
  'winner': 'England',
  'margin': '10 wickets',
  'ground': 'Adelaide',
  'matchDate': 'Nov 10, 2022',
  'scorecard': 'T20I # 1878'},
 {'team1': 'England',
  'team2': 'Pakistan',
  'winner': 'England',
  'margin': '5 wickets',
  'ground': 'Melbourne',
  'matchDate': 'Nov 13, 2022',
  'scorecard': 'T20I # 1879'}]

In [5]:
#now lets create a data frame for the summary
with open("t20_wc_match_results.json") as f:
    data=json.load(f)
df_match= pd.DataFrame(data[0]["matchSummary"])
df_match

,team1,team2,winner,margin,ground,matchDate,scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830
5,Sri Lanka,U.A.E.,Sri Lanka,79 runs,Geelong,"Oct 18, 2022",T20I # 1832
6,Ireland,Scotland,Ireland,6 wickets,Hobart,"Oct 19, 2022",T20I # 1833
7,West Indies,Zimbabwe,West Indies,31 runs,Hobart,"Oct 19, 2022",T20I # 1834
8,Netherlands,Sri Lanka,Sri Lanka,16 runs,Geelong,"Oct 20, 2022",T20I # 1835
9,Namibia,U.A.E.,U.A.E.,7 runs,Geelong,"Oct 20, 2022",T20I # 1836
10,Ireland,West Indies,Ireland,9 wickets,Hobart,"Oct 21, 2022",T20I # 1837
11,Scotland,Zimbabwe,Zimbabwe,5 wickets,Hobart,"Oct 21, 2022",T20I # 1838
12,Australia,New Zealand,New Zealand,89 runs,Sydney,"Oct 22, 2022",T20I # 1839
13,Afghanistan,England,England,5 wickets,Perth,"Oct 22, 2022",T20I # 1840
14,Ireland,Sri Lanka,Sri Lanka,9 wickets,Hobart,"Oct 23, 2022",T20I # 1841
15,India,Pakistan,India,4 wickets,Melbourne,"Oct 23, 2022",T20I # 1842
16,Bangladesh,Netherlands,Bangladesh,9 runs,Hobart,"Oct 24, 2022",T20I # 1843
17,South Africa,Zimbabwe,no result,,Hobart,"Oct 24, 2022",T20I # 1844
18,Australia,Sri Lanka,Australia,7 wickets,Perth,"Oct 25, 2022",T20I # 1845
19,England,Ireland,Ireland,5 runs,Melbourne,"Oct 26, 2022",T20I # 1846
20,Afghanistan,New Zealand,abandoned,,Melbourne,"Oct 26, 2022",T20I # 1846a
21,Bangladesh,South Africa,South Africa,104 runs,Sydney,"Oct 27, 2022",T20I # 1847
22,India,Netherlands,India,56 runs,Sydney,"Oct 27, 2022",T20I # 1848
23,Pakistan,Zimbabwe,Zimbabwe,1 run,Perth,"Oct 27, 2022",T20I # 1849
24,Afghanistan,Ireland,abandoned,,Melbourne,"Oct 28, 2022",T20I # 1849a
25,Australia,England,abandoned,,Melbourne,"Oct 28, 2022",T20I # 1849b
26,New Zealand,Sri Lanka,New Zealand,65 runs,Sydney,"Oct 29, 2022",T20I # 1850
27,Bangladesh,Zimbabwe,Bangladesh,3 runs,Brisbane,"Oct 30, 2022",T20I # 1851
28,Netherlands,Pakistan,Pakistan,6 wickets,Perth,"Oct 30, 2022",T20I # 1852
29,India,South Africa,South Africa,5 wickets,Perth,"Oct 30, 2022",T20I # 1853
30,Australia,Ireland,Australia,42 runs,Brisbane,"Oct 31, 2022",T20I # 1855
31,Afghanistan,Sri Lanka,Sri Lanka,6 wickets,Brisbane,"Nov 1, 2022",T20I # 1856
32,England,New Zealand,England,20 runs,Brisbane,"Nov 1, 2022",T20I # 1858
33,Netherlands,Zimbabwe,Netherlands,5 wickets,Adelaide,"Nov 2, 2022",T20I # 1859
34,Bangladesh,India,India,5 runs,Adelaide,"Nov 2, 2022",T20I # 1860
35,Pakistan,South Africa,Pakistan,33 runs,Sydney,"Nov 3, 2022",T20I # 1861
36,Ireland,New Zealand,New Zealand,35 runs,Adelaide,"Nov 4, 2022",T20I # 1862
37,Australia,Afghanistan,Australia,4 runs,Adelaide,"Nov 4, 2022",T20I # 1864
38,England,Sri Lanka,England,4 wickets,Sydney,"Nov 5, 2022",T20I # 1867
39,Netherlands,South Africa,Netherlands,13 runs,Adelaide,"Nov 6, 2022",T20I # 1871
40,Bangladesh,Pakistan,Pakistan,5 wickets,Adelaide,"Nov 6, 2022",T20I # 1872
41,India,Zimbabwe,India,71 runs,Melbourne,"Nov 6, 2022",T20I # 1873
42,New Zealand,Pakistan,Pakistan,7 wickets,Sydney,"Nov 9, 2022",T20I # 1877
43,England,India,England,10 wickets,Adelaide,"Nov 10, 2022",T20I # 1878
44,England,Pakistan,England,5 wickets,Melbourne,"Nov 13, 2022",T20I # 1879

In [6]:
#check how many elements it has---- we can do this by using the method called "shape"
df_match.shape

(45, 7)

In [7]:
#use score card as a key for the above particular data frame because to identify uniquely, treat it as match id because we can connect with other tables

In [8]:
#rename the scorecard column

In [9]:
df_match.rename({"scorecard":"match_id"},axis=1, inplace= True)   #we have to use inplace=true otherwise it creates a new dataframe/table
df_match.head() #to access top 5 rows

,team1,team2,winner,margin,ground,matchDate,match_id
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [10]:
#create dictionary to store the items or elements
match_ids_dict={}
for index,row in df_match.iterrows():
    key1=row["team1"]+ " Vs " +row["team2"]
    key2=row["team2"]+" Vs "+row["team1"]
    match_ids_dict[key1]=row["match_id"]
    match_ids_dict[key2]=row["match_id"]
match_ids_dict

{'Namibia Vs Sri Lanka': 'T20I # 1823',
 'Sri Lanka Vs Namibia': 'T20I # 1823',
 'Netherlands Vs U.A.E.': 'T20I # 1825',
 'U.A.E. Vs Netherlands': 'T20I # 1825',
 'Scotland Vs West Indies': 'T20I # 1826',
 'West Indies Vs Scotland': 'T20I # 1826',
 'Ireland Vs Zimbabwe': 'T20I # 1828',
 'Zimbabwe Vs Ireland': 'T20I # 1828',
 'Namibia Vs Netherlands': 'T20I # 1830',
 'Netherlands Vs Namibia': 'T20I # 1830',
 'Sri Lanka Vs U.A.E.': 'T20I # 1832',
 'U.A.E. Vs Sri Lanka': 'T20I # 1832',
 'Ireland Vs Scotland': 'T20I # 1833',
 'Scotland Vs Ireland': 'T20I # 1833',
 'West Indies Vs Zimbabwe': 'T20I # 1834',
 'Zimbabwe Vs West Indies': 'T20I # 1834',
 'Netherlands Vs Sri Lanka': 'T20I # 1835',
 'Sri Lanka Vs Netherlands': 'T20I # 1835',
 'Namibia Vs U.A.E.': 'T20I # 1836',
 'U.A.E. Vs Namibia': 'T20I # 1836',
 'Ireland Vs West Indies': 'T20I # 1837',
 'West Indies Vs Ireland': 'T20I # 1837',
 'Scotland Vs Zimbabwe': 'T20I # 1838',
 'Zimbabwe Vs Scotland': 'T20I # 1838',
 'Australia Vs New Zealand': 'T20I # 1839',
 'New Zealand Vs Australia': 'T20I # 1839',
 'Afghanistan Vs England': 'T20I # 1840',
 'England Vs Afghanistan': 'T20I # 1840',
 'Ireland Vs Sri Lanka': 'T20I # 1841',
 'Sri Lanka Vs Ireland': 'T20I # 1841',
 'India Vs Pakistan': 'T20I # 1842',
 'Pakistan Vs India': 'T20I # 1842',
 'Bangladesh Vs Netherlands': 'T20I # 1843',
 'Netherlands Vs Bangladesh': 'T20I # 1843',
 'South Africa Vs Zimbabwe': 'T20I # 1844',
 'Zimbabwe Vs South Africa': 'T20I # 1844',
 'Australia Vs Sri Lanka': 'T20I # 1845',
 'Sri Lanka Vs Australia': 'T20I # 1845',
 'England Vs Ireland': 'T20I # 1846',
 'Ireland Vs England': 'T20I # 1846',
 'Afghanistan Vs New Zealand': 'T20I # 1846a',
 'New Zealand Vs Afghanistan': 'T20I # 1846a',
 'Bangladesh Vs South Africa': 'T20I # 1847',
 'South Africa Vs Bangladesh': 'T20I # 1847',
 'India Vs Netherlands': 'T20I # 1848',
 'Netherlands Vs India': 'T20I # 1848',
 'Pakistan Vs Zimbabwe': 'T20I # 1849',
 'Zimbabwe Vs Pakistan': 'T20I # 1849',
 'Afghanistan Vs Ireland': 'T20I # 1849a',
 'Ireland Vs Afghanistan': 'T20I # 1849a',
 'Australia Vs England': 'T20I # 1849b',
 'England Vs Australia': 'T20I # 1849b',
 'New Zealand Vs Sri Lanka': 'T20I # 1850',
 'Sri Lanka Vs New Zealand': 'T20I # 1850',
 'Bangladesh Vs Zimbabwe': 'T20I # 1851',
 'Zimbabwe Vs Bangladesh': 'T20I # 1851',
 'Netherlands Vs Pakistan': 'T20I # 1852',
 'Pakistan Vs Netherlands': 'T20I # 1852',
 'India Vs South Africa': 'T20I # 1853',
 'South Africa Vs India': 'T20I # 1853',
 'Australia Vs Ireland': 'T20I # 1855',
 'Ireland Vs Australia': 'T20I # 1855',
 'Afghanistan Vs Sri Lanka': 'T20I # 1856',
 'Sri Lanka Vs Afghanistan': 'T20I # 1856',
 'England Vs New Zealand': 'T20I # 1858',
 'New Zealand Vs England': 'T20I # 1858',
 'Netherlands Vs Zimbabwe': 'T20I # 1859',
 'Zimbabwe Vs Netherlands': 'T20I # 1859',
 'Bangladesh Vs India': 'T20I # 1860',
 'India Vs Bangladesh': 'T20I # 1860',
 'Pakistan Vs South Africa': 'T20I # 1861',
 'South Africa Vs Pakistan': 'T20I # 1861',
 'Ireland Vs New Zealand': 'T20I # 1862',
 'New Zealand Vs Ireland': 'T20I # 1862',
 'Australia Vs Afghanistan': 'T20I # 1864',
 'Afghanistan Vs Australia': 'T20I # 1864',
 'England Vs Sri Lanka': 'T20I # 1867',
 'Sri Lanka Vs England': 'T20I # 1867',
 'Netherlands Vs South Africa': 'T20I # 1871',
 'South Africa Vs Netherlands': 'T20I # 1871',
 'Bangladesh Vs Pakistan': 'T20I # 1872',
 'Pakistan Vs Bangladesh': 'T20I # 1872',
 'India Vs Zimbabwe': 'T20I # 1873',
 'Zimbabwe Vs India': 'T20I # 1873',
 'New Zealand Vs Pakistan': 'T20I # 1877',
 'Pakistan Vs New Zealand': 'T20I # 1877',
 'England Vs India': 'T20I # 1878',
 'India Vs England': 'T20I # 1878',
 'England Vs Pakistan': 'T20I # 1879',
 'Pakistan Vs England': 'T20I # 1879'}

In [12]:
df_match.to_csv('dim_match_summary.csv', index = False)

In [ ]:
#now the main task is to export this data into CSV file, before that we have to process the batting summary

**Batting Summary**

In [ ]:
#open batting summary json file
with open("t20_wc_batting_summary.json") as f:
    data=json.load(f)
data

In [ ]:
# here we have details of all matches to get the summary of one match we have to execute the following code
with open("t20_wc_batting_summary.json") as f:
    data=json.load(f)

    for rec in data:
        rec["battingSummary"]
data

In [ ]:
#append ever thing into one array that is merge all the matches
#to create a single list in pandas we use the code
with open("t20_wc_batting_summary.json") as f:
    data=json.load(f)

    all_records=[]
         
    for rec in data:
        all_records.extend(rec["battingSummary"])
        #extend is used when we have one array and we are appending another array
all_records

In [ ]:
#now create a data frame with the give data
with open("t20_wc_batting_summary.json") as f:
    data=json.load(f)

    all_records=[]
         
    for rec in data:
        all_records.extend(rec["battingSummary"])
df_batting=pd.DataFrame(all_records)
df_batting.head()

In [ ]:
df_batting.head(11)

In [ ]:
# now w have to convert the dismissal column to out ir not out column if the box is empty then the player is not out and if the box have some thing the player out.
df_batting["out/not_out"]= df_batting.dismissal.apply(lambda x:"out" if len(x)>0 else "not_out")
df_batting.head()

In [ ]:
df_batting.head(11)

In [ ]:
# now there is no need of dismissal column so drop that column
df_batting.drop(columns=["dismissal"],inplace=True)
df_batting.head(11)

In [ ]:
# now if you observe there are some issue with batsman name as it contains the special characters
df_batting["batsmanName"]=df_batting["batsmanName"].apply(lambda x: x.replace("â€",""))
df_batting["batsmanName"]=df_batting["batsmanName"].apply(lambda x: x.replace("/xa0",""))
df_batting.head(11)

In [ ]:
# now the main task is to connect this particular data frame to the previously modified match data frame in both we have match column same so we have to merge ,

In [ ]:
# now lts check the match_id for a particular match
match_ids_dict["Namibia Vs Sri Lanka"]

In [ ]:

df_batting["match_id"]= df_batting["match"].map(match_ids_dict)
df_batting.head()
#now we got the match_id's for all the batting table also

In [ ]:
#now we have to export this particular file into CSV file
df_batting.to_csv("fact_batting_summary.csv", index = False)

In [ ]:
# now we have to process the bowling summary
import json
with open('t20_wc_bowling_summary.json') as f:
    data = json.load(f)
    all_records = []
    for rec in data:
        all_records.extend(rec['bowlingSummary'])
all_records[:2]

In [ ]:
df_bowling = pd.DataFrame(all_records)
print(df_bowling.shape) #shape of the table
df_bowling.head()  # returns the top 5 elements

In [ ]:
df_bowling['match_id'] = df_bowling['match'].map(match_ids_dict)   # here we are adding the elements with the match ids
df_bowling.head()

In [ ]:
df_bowling.to_csv('fact_bowling_summary.csv', index = False)   # download the csv file of the data

In [ ]:
# now we have to process the  players information

In [ ]:
with open('t20_wc_player_info.json') as f:
    data = json.load(f)

In [ ]:
df_players = pd.DataFrame(data)

print(df_players.shape)
df_players.head(10)

In [ ]:
# we can observe some weird characters over the names of the players we have to clean them

In [ ]:
df_players['name'] = df_players['name'].apply(lambda x: x.replace('â€', ''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('†', ''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('\xa0', ''))
df_players.head(10)

In [ ]:
df_players[df_players['team'] == 'India']   # now selecting the players from india

In [ ]:
df_players.to_csv('dim_players_no_images.csv', index = False)   # downloading the csv file

In [ ]:
#Successfully data processing using pandas is completed now further steps need to be done in power BI

In [ ]:
#thankyou